### PR TITLE
gh-350 Set a custom profile to show in the profile on screen entry

### PR DESCRIPTION
**Pull request by GBishop-PHSA**
gh-350 Allow a default selection for the Profile droplist. The user can set a default.profile property at any level of the catalogue item hierarchy and the UI searches for these properties and sets default values in the profile droplist for Model, Class and Element if a Custom Profile name matches the property value. If no match is found, the existing 'default' selection is set in the droplist.

### CODE REVIEW

**Comment by jamesrwelch** [comment]
@GBishop-PHSA This seems like a really nice feature - I especially like that by setting the property in some of our custom imports we can control the way the model / class / element is presented. I'm playing with the branch now and I can't seem to get it working - we've made some changes to the back end which may have inadvertently broken it? Or maybe I've not followed the instructions above correctly. Would you be able to take a look?

**Review by jamesrwelch — CHANGES_REQUESTED** [review]
@GBishop-PHSA This works really nicely.  I've merged to the latest version of develop.  I wonder if you could just fix the few lint errors that are stopping a nice green tick?  Running
```
npm run eslint-report
```
will give you the report (eslint_report.xml) - don't worry about the warnings, but could you fix any 'error' messages on your new code?  I had a quick scan and it looks like they're all fairly straightforward to resolve.  Thanks!

**Comment by GBishop-PHSA** [comment]
@jamesrwelch I've fixed the errors from the lint report

**Review by jamesrwelch — APPROVED** [review]
Lovely stuff - thank you very much!

**Pull request merged**
