### PR TITLE
Show version numbers in view/edit profiles dropdown

### PR DESCRIPTION
**Pull request by joe-crawford**
Add version number to profile view/edit dropdown and allow backend to filter versions of profiles displayed (resolves gh-493)

### CODE REVIEW

**Comment by joe-crawford** [comment]
Depends on https://github.com/MauroDataMapper/mdm-resources/pull/56.

Also depends on https://github.com/MauroDataMapper/mdm-core/pull/293 (merged to develop).

**Review by jamesrwelch — CHANGES_REQUESTED** [review]
One thing that seems to have stopped working with this commit... is that when you add a new profile, it doesn't properly route the next page to display the new profile properly... Are you able to reproduce this and work out this issue?

**Comment by joe-crawford** [comment]
> One thing that seems to have stopped working with this commit... is that when you add a new profile, it doesn't properly route the next page to display the new profile properly... Are you able to reproduce this and work out this issue?

Yes I had noticed similar issues, although I think they were already occurring on develop branch (raised as gh-503). Looking again I have realised it is related to how the new configurable default profile is set. The above commit resolves it for me however as the issue was sometimes intermittent, so could you check if this resolves it for you?

**Comment by joe-crawford** [comment]
Commit 864cba2 contains a change to gh-350 Default dynamic profile view configuration:

The API property to set is still `ui.default.profile.namespace`; it must be publicly readable.

As the profile display names may not be unique, the default profiles are now set by:

| namespace | key | value | example value |
|-|-|-|-|
| value of `ui.default.profile.namespace` | `namespace` | profile provider `namespace` | `uk.ac.ox.softeng.maurodatamapper.profile.provider` |
| value of `ui.default.profile.namespace` | `name` | profile provider `name` | `A%20Dynamic%20Profile` |
| value of `ui.default.profile.namespace` | `version` | profile provider `version` | `1.0.0` |

**Review by jamesrwelch — APPROVED** [review]
Amazing work, well done!

**Pull request merged**
