### PR TITLE
gh-808 Attachment file size limit validation

### PR DESCRIPTION
**Pull request by GBishop-PHSA**
gh-808 When users upload a file that exceeds the mazimum file size limit, the will receive a helpful error message based on a value set in the admin configuration.

### CODE REVIEW

**Comment by joe-crawford** [comment]
Hi @GBishop-PHSA, thanks for this contribution. I'm running `feature/gh-808` of core and the UI but I haven't managed to see the message when uploading a large file.

I can see errors in the console when loading the Annotations tab, one is
```
ERROR SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at AttachmentListComponent.loadAttachmentFileSizeLimit (attachment-list.component.ts:317:41)
```

However when uploading a larger file (170MB so shouldn't be over the limit) I'm also getting another error:
```
ERROR RangeError: Invalid array length
    at Function.from (<anonymous>)
    at reader.onload (attachment-list.component.ts:286:29)
    at _ZoneDelegate.invoke (zone.js:375:26)
    at Object.onInvoke (core.mjs:26274:33)
    at _ZoneDelegate.invoke (zone.js:374:52)
    at Zone.runGuarded (zone.js:144:47)
    at FileReader.<anonymous> (zone.js:128:29)
```

Is this something that you've seen? 

I'm using Google Chrome 115 on macOS.

**Comment by GBishop-PHSA** [comment]
@joe-crawford I've fixed the json parsing exception. I wasn't able to repeat the array length error. I think that code change was added from May 2021.

**Comment by joe-crawford** [comment]
Thanks for the update @GBishop-PHSA, I'm trying this again on your branch of mdm-core and mdm-ui, I'm trying to test with the default value of 200MB set in mdm-core, when trying to upload a large file again I'm seeing the same `Invalid array length` error as last time. I'm on latest Chrome on macOS. Do you have any suggestions for how to test this locally?

**Comment by joe-crawford** [comment]
Screenshot 2024-04-04 at 16 12 10
Each time I click the green tick to upload the file, the Invalid array length error repeats, it takes about a second after clicking to happen.

File size is 210MB so was hoping it would trigger the message.

**Comment by joe-crawford** [comment]
I think the issue may be with the existing
```fileContents: Array.from(fileBytes)```
as looking at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_array_length:
>For [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) the maximum length is 2^32-1

and perhaps the Chrome limit is smaller than this? 

Would it be possible to fix this, or if not in this issue, at least adjust the default down so it's less than the upper array limit size on Chrome?

**Review by joe-crawford — APPROVED** [review]
Thanks for this and sorry for the delay in merging!

Using Firefox on macOS I've been able to see the warning successfully when trying to upload an oversized file with the default limit (190MB). As mentioned Chrome on macOS (arm64) fails on smaller files due to the array issue. A workaround for now could be lowering the default limit to something that works on macOS Chrome. Will leave that for another PR.

**Pull request merged**
