### PR TITLE
Feature/mc 9735

### PR DESCRIPTION
**Pull request by gammonpeter**
Added Features to support new subscription changes

### CODE REVIEW

**Review by olliefreeman — APPROVED** [review]
I’m gonna leave it to James to approve, I trust it all works.

**Comment by jamesrwelch** [comment]
Trying to run this on develop branch of mc-core and the feature/mc-9735 branch of mdm-resources.  Getting 404 when posting to `/api/subscribedCatalogues` when creating a new subscription.  Should that be `/api/admin/subscribedCatalogues`?

**Comment by gammonpeter** [comment]
Awaitng MDM-Resouces merge

**Comment by jamesrwelch** [comment]
> Awaitng MDM-Resouces merge

Is this an issue with the MDM Resources PR though?  That's pointing at `api/subscribedCatalogues`, but the Core code seems to imply `api/admin/subscribedCatalogues`

**Comment by joe-crawford** [comment]
After the mdm-resources merge a few minutes ago, I'm trying with develop of mdm-resources and feature/mc-9735 of mdm-ui. I'm getting this error when trying to start the UI (ng serve):

```
Error: src/app/model/federated-data-model.ts:40:33 - error TS2339: Property 'version' does not exist on type 'AvailableDataModel'.

40       this.version = available?.version;
                                   ~~~~~~~
```

**Review by joe-crawford — APPROVED** [review]
I've tested and all these changes look good so will approve.

**Pull request merged**
