### PR TITLE
gh-418 Add autocomplete style search to content editors

### LINKED ISSUE #418: Create internal links when editing long text more easily with a shortcut
A bit like in an IDE where you can press e.g. Ctrl+Space, and start typing, and it will give you suggestions for appropriate content.  It would be very handy to be able to do this here, using a Lucene prefix search (a suitable endpoint may need to be created if one doesn't already exist).
See also #417

### PR DESCRIPTION
**Pull request by pjmonks**
Resolves #418 

**Note:** this depends on PR MauroDataMapper/mdm-resources#69

image

New autocomplete-style dialog can be used in the Markdown/HTML editors to search for catalogue items and then create links to them in the content editors. Can be triggered by either a keyboard shortcut (Ctrl+Space) or toolbar button.

To activate autocomplete, the `mdm-content-editor` needs to be provided with a root catalogue item to base all searches on. This means it is currently supported on the usual model domain types at the moment to support their description fields.

* Clean up code for existing Markdown and HTML editors
* Reorganise content editors into their own module
* Capture hotkey shortcuts to respond to Ctrl+Space to trigger autocomplete
* Create new search dialog to contain autocomplete control
* Create new function in path service to create path from breadcrumbs element
* Apply root catalogue element to content editors for autocomplete search

### CODE REVIEW

**Review by jamesrwelch — COMMENTED** [review]
Ok, I've had a play.  The UI component of this mostly works ok - I've experienced a few issues  where searching seems to stop, and clicking on the resultant link gave me an error.  But more importantly, the back-end doesn't appear to give me the results I was hoping for, so I'm going to give this feature a bit more thought before we merge it

**Comment by pjmonks** [comment]
Rebased this PR to be up to date with `develop`, particular now the UI is on Angular 14 cc @jamesrwelch

**Comment by jamesrwelch** [comment]
Sorry, @pjmonks, after merging the last PR there are now a load of conflicts on this one - would you be able to take a look, please?  Hopefully fairly straightforward 🤞

**Comment by pjmonks** [comment]
@jamesrwelch I've fixed all the merge conflicts, please try again.

**Review by jamesrwelch — COMMENTED** [review]
This works really nicely - the code looks sensible too.  
Two reflections:
- It's not completely obvious if there are no search results found
- If we're in a model that's within a versioned folder, we should really search within that.  Maybe that's a change to the back-end we could make

**Comment by pjmonks** [comment]
@jamesrwelch I've updated to handle your first suggestion:

image

For handling the case of a Versioned Folder being the root for the search results, could this be a separate issue? I'm not immediately sure how we would identify that a model is under a versioned folder.

**Review by jamesrwelch — APPROVED** [review]
This all looks good - and the change to add a 'no results' message is clean.  Thank you!

**Pull request merged**
