### PR TITLE
MC-9719 Fix profile validation issues

### PR DESCRIPTION
**Pull request by pjmonks**
* Use correct fieldTotal property for counting validation errors
* Don't validate the empty profile immediately on open, only when clicking the validate button

### CODE REVIEW

**Comment by joe-crawford** [comment]
Thanks @pjmonks.

Looking at how this works, perhaps something more is needed. Not validating the (possibly new/empty) profile on opening is to avoid the user immediately seeing red 'field required' errors for the blank fields. But as validation is optional, now they might click Save and miss that a field is required if they don't spot the `*`.

Perhaps we could make an additional change, so the user is required to click Validate at least once before clicking Save. So Save is grey to start with, then is un-greyed on validation, even if it fails. 

@pjmonks, @jamesrwelch Do you think the above makes sense, or is that too many clicks?

**Comment by jamesrwelch** [comment]
@pjmonks , @joe-crawford 

This is a difficult one.  We don't want to force people to validate the entry, but helping them create valid entries might be useful.  How about:
- We don't validate unless the validate button is clicked.
- The user can click 'save' at any point.
- When the user clicks save, we run a validation.  If the form entry is invalid, we ask pop up a box telling the user that the values are invalid - would they like to continue, or edit their response?  If they wish to save without validating, we continue; if they wish to continue editing we give them the hints as though they'd clicked the validate button.

**Comment by joe-crawford** [comment]
Thanks @pjmonks and @jamesrwelch. I suppose the solution is either as James suggests, or perhaps I'm overcomplicating it in which case keeping the PR as it is might be best. Will leave to you to decide.

**Comment by pjmonks** [comment]
@jamesrwelch , @joe-crawford I've updated the profile dialog as James has suggested:

image

If validation errors are found when saving, the user gets a chance to confirm whether to actually continue or correct the issues found.

**Review by joe-crawford — APPROVED** [review]
@pjmonks, sorry for the delay in getting to this. Looks good, thank you!

**Pull request merged**
