### PR TITLE
#343 #344 updated password tab order and redirected back to profile home

### PR DESCRIPTION
**Pull request by gammonpeter**

### CODE REVIEW

**Comment by gammonpeter** [comment]
npm install required for this to work as an update to a package is required

**Comment by jamesrwelch** [comment]
Can we have a quick call about this one first thing tomorrow?  Would like to get it merged, but have a couple of questions still...

**Comment by jamesrwelch** [comment]
Took a while to get my dependencies all in order...
@olliefreeman may need to check with @gammonpeter

**Review by jamesrwelch — APPROVED** [review]
Now I've got the dependencies all sorted, this works very nicely - good work

**Pull request merged**
