### PR TITLE
gh-857 Add full and correct breadcrumb trail for each Mauro item displayed

### LINKED ISSUE #857: Add tree/folder path to items as a breadcrumb trail
# Dependencies

Depends on:

- MauroDataMapper/mdm-core#452

# Description

The NHS Data Dictionary models and items are dense in hierarchy, and the DD versioned folder can be branched and finalised multiple times to create multiple hierarchies. This means that when navigating around items in the dictionary, it is hard to keep track of where the item is located - currently the model tree and the item details on the right-side of the screen are not always synchronised.

This can be improved by showing the folder path to the item along with the sub-item breadcrumb. For example:

Image

This currently shows the breadcrumb `Classes and Attributes (Draft) / ACCOMODATION` for the data element `ACCOMODATION STATUS CODE`. However, it does not say which _version_ of `Classes and Attributes` is being viewed - a finalised version of the DD? A branch? Which branch? Which sub-folders? etc

### PR DESCRIPTION
**Pull request by pjmonks**
Resolves #857 

This pull request depends on:

- MauroDataMapper/mdm-core#452
- MauroDataMapper/mdm-resources#112

# Changes

- Use ancestors endpoints to create the full location path to an item
- Include branch, versions and version tags for models where applicable
- Location path components are hyperlinks that jump to each other item correctly
- Remove old breadcrumbs for model child items - these are now automatically included in the location paths
- Fix lint issues in `model-header.component`

image

### CODE REVIEW

**Comment by jamesrwelch** [comment]
I'm getting some odd formatting / layout quirks:
Screenshot 2024-05-08 at 09 59 28
Is this easy to resolve?

**Comment by jamesrwelch** [comment]
@pjmonks Another question related to styling - at the moment the path is injected into the page once it's loaded - this is a little slower on my large testing instance, which causes the rest of the page contents to move downwards after loading.  Is it possible to put a placeholder in while the location is loading?  Obviously it might spill into two lines and we can't predict that, but it might help most of the time.

**Comment by pjmonks** [comment]
@jamesrwelch I've adjusted the styling to hopefully work on Safari, though I can't say for definite - I've at least changed how the breadcrumb horizontally flows. I've also added a placeholder while the location path is being fetched.

As I was testing, I noticed that the breadcrumb trail for model sub-items may sometimes appear in the wrong order, such as a Data Element link coming before a Data Class link. This is an issue with the backend, which I've added here:

- MauroDataMapper/mdm-core#458

I don't this will should affect how the UI presents the information once that is fixed.

**Comment by jamesrwelch** [comment]
@pjmonks The wobbliness is now gone, thank you.  And the "loading..." placeholder works nicely on my slow instance.  I wonder, do we need the last part of the path, which is the object you're currently looking at?

**Comment by pjmonks** [comment]
@jamesrwelch I've updated to remove the item actually on display from the breadcrumb path, this should hopefully be ready to review.

Jenkins is complaining of tests failing, this is actually related to the code coverage plugin again if you could fix that please.

**Comment by pjmonks** [comment]
@jamesrwelch Updated with new Jenkins change for code coverage, this should be the last fix 🤞

**Review by jamesrwelch — APPROVED** [review]
Great!  This will be really useful for large models and versioned folders

**Pull request merged**
