### PR TITLE
gh-742 Code updates to support Angular 14 typed forms

### LINKED ISSUE #742: Use Angular 14 Typed Forms
Angular 14 introduces Typed Forms:  https://angular.io/guide/typed-forms
If we were to use these in our code we'd get better type-checking and hopefully better code quality.
The current code uses the default `UntypedForm` in the few places where Forms are actually defined - these need converting to proper Typed versions, and there are probably other places in the code where explicit Form definitions could be introduced.

### PR DESCRIPTION
**Pull request by pjmonks**
Resolves #742 

Note that some existing forms have _not_ been updated as they seem more complex, these are:

- `mdm-new-version`
- `mdm-openid-connect-provider`
- `mdm-create-term-relationship-dialog`

All other uses of `FormGroup` have been updated to be strongly typed.

### CODE REVIEW

**Comment by jamesrwelch** [comment]
@pjmonks The conflicts on this branch look fairly straightforward, but could you resolve them so I don't make any horrible mistakes?  Thanks!

**Review by jamesrwelch — CHANGES_REQUESTED** [review]
This is really great work - this will help make our code much more reliable.  I've played with all the forms affected by this change, and unfortunately I've found one that no-longer works - the one for adding / editing a subscribed catalogue.  If you can fix that one, then I think this is good to go.  Thanks!

**Review by jamesrwelch — CHANGES_REQUESTED** [review]
Should there be more to this change?  The max / min in the control work, but I can't get it to show the red error messages?

**Comment by pjmonks** [comment]
> Should there be more to this change? The max / min in the control work, but I can't get it to show the red error messages?

There are two ways to enter a number. Either click on the up/down arrows of the numeric control - then the min/max constraints will not allow you to go above/below those values.

Alternatively, type in a number manually in the text input. Then leave focus of that field and the validation should kick in, forcing you to enter a value within those constraints.

**Comment by jamesrwelch** [comment]
You're right - it's the changing focus bit that I'd missed.   I'm happy with this.

**Review by jamesrwelch — APPROVED** [review]

**Pull request merged**
